/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/app/theme/manaredTheme.ts
 * Command: astryx theme build src/app/theme/manaredTheme.ts
 * Generated: 2026-07-05T23:52:37.327Z
 */

// Generated by astryx theme build
export {};

declare module "@astryxdesign/core/Heading" {
  interface XDSHeadingLevelMap {
    "1": true;
    "2": true;
    "3": true;
    "4": true;
    "5": true;
    "6": true;
  }
}
