/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/app/theme/manaredTheme.ts
 * Command: astryx theme build src/app/theme/manaredTheme.ts
 * Generated: 2026-07-07T22:36:02.095Z
 */

import type { DefinedTheme } from "@astryxdesign/core/theme";
import type { IconRegistry } from "@astryxdesign/core/Icon";
export declare const neutralIconRegistry: IconRegistry;
export declare const manaredTheme: DefinedTheme;
